version: '3.9'

services:
  tljh-server:
    image: tljh/server
    build:
      context: .
      args:
        - ADMIN_USER=${ADMIN_USER:-admin}
    ports:
      - "12000:80"
    stop_signal: SIGRTMIN+3
