version: '3.9'

services:
  jupyterhub:
    image: "${COMPOSE_PROJECT_NAME}/jupyterhub"
    build: .
    volumes:
      - ./jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py:ro
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: '1G'
        reservations:
          cpus: '1'
          memory: '1G'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5m
    command:
      - jupyterhub
      - --config=/etc/jupyterhub/jupyterhub_config.py
    ports:
      - "8000"

  jupyter-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jupyterhub
    ports:
      - "4000:4000"
